wip

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,102 +45,102 @@ jobs:
           DIFFS=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
           echo "Post diff, pre grep"
 
-          SERVICES_CHANGED=$(echo "$DIFFS" | grep -m 1 "^services/")
+          SERVICES_CHANGED=$(echo "$DIFFS" | grep -m 1 "services")
           echo "post grep"
 
 
           if [ -n "$SERVICES_CHANGED" ]; then
             echo "Changed"
-            docker build services/artifacts -t ghcr.io/${{ github.repository }}/artifacts:${{ github.sha }}
-            docker build services/fund-accounts -t ghcr.io/${{ github.repository }}/fund-accounts:${{ github.sha }}
-            export INFRA_TAG=${{ github.sha }}
+            # docker build services/artifacts -t ghcr.io/${{ github.repository }}/artifacts:${{ github.sha }}
+            # docker build services/fund-accounts -t ghcr.io/${{ github.repository }}/fund-accounts:${{ github.sha }}
+            # export INFRA_TAG=${{ github.sha }}
           fi
 
           echo "Not changed"
 
-          docker compose up -d
+          # docker compose up -d
 
       # The mine service should exit with a zero error code.
-      - name: Check mine service
-        run: |
-          DIRNAME=$(basename $(pwd))
-          MINE_ERROR=$(docker wait $DIRNAME-mine-1)
+      # - name: Check mine service
+      #   run: |
+      #     DIRNAME=$(basename $(pwd))
+      #     MINE_ERROR=$(docker wait $DIRNAME-mine-1)
 
-          if [ $MINE_ERROR -ne 0 ]; then
-            echo "Mine service exited with an error"
-            exit 1
-          fi
+      #     if [ $MINE_ERROR -ne 0 ]; then
+      #       echo "Mine service exited with an error"
+      #       exit 1
+      #     fi
 
-      # The fund-accounts should exit with a zero error code.
-      - name: Check fund Accounts service
-        run: |
-          DIRNAME=$(basename $(pwd))
-          FUND_ACCOUNTS_ERROR=$(docker wait $DIRNAME-fund-accounts-1)
+      # # The fund-accounts should exit with a zero error code.
+      # - name: Check fund Accounts service
+      #   run: |
+      #     DIRNAME=$(basename $(pwd))
+      #     FUND_ACCOUNTS_ERROR=$(docker wait $DIRNAME-fund-accounts-1)
 
-          if [ $FUND_ACCOUNTS_ERROR -ne 0 ]; then
-            echo "Fund accounts service exited with an error"
-            exit 1
-          fi
+      #     if [ $FUND_ACCOUNTS_ERROR -ne 0 ]; then
+      #       echo "Fund accounts service exited with an error"
+      #       exit 1
+      #     fi
 
-      # The ethereum service should be running.
-      - name: Check ethereum service
-        run: |
-          if [ -z "$(docker compose ps -q ethereum)" ]; then
-            echo "Ethereum service exited unexpectedly"
-            exit 1
-          fi
+      # # The ethereum service should be running.
+      # - name: Check ethereum service
+      #   run: |
+      #     if [ -z "$(docker compose ps -q ethereum)" ]; then
+      #       echo "Ethereum service exited unexpectedly"
+      #       exit 1
+      #     fi
 
-      # The artifacts service should be running.
-      - name: Check artifacts service
-        run: |
-          if [ -z "$(docker compose ps -q artifacts)" ]; then
-            echo "Artifacts service exited unexpectedly"
-            exit 1
-          fi
+      # # The artifacts service should be running.
+      # - name: Check artifacts service
+      #   run: |
+      #     if [ -z "$(docker compose ps -q artifacts)" ]; then
+      #       echo "Artifacts service exited unexpectedly"
+      #       exit 1
+      #     fi
 
-      # The checkpoint-bot service should be running.
-      - name: Check checkpoint-bot service
-        run: |
-          if [ -z "$(docker compose ps -q checkpoint-bot)" ]; then
-            echo "Checkpoint bot service exited unexpectedly"
-            exit 1
-          fi
+      # # The checkpoint-bot service should be running.
+      # - name: Check checkpoint-bot service
+      #   run: |
+      #     if [ -z "$(docker compose ps -q checkpoint-bot)" ]; then
+      #       echo "Checkpoint bot service exited unexpectedly"
+      #       exit 1
+      #     fi
 
-      # The data service should be running.
-      - name: Check data service
-        run: |
-          if [ -z "$(docker compose ps -q data)" ]; then
-            echo "Data service exited unexpectedly"
-            exit 1
-          fi
+      # # The data service should be running.
+      # - name: Check data service
+      #   run: |
+      #     if [ -z "$(docker compose ps -q data)" ]; then
+      #       echo "Data service exited unexpectedly"
+      #       exit 1
+      #     fi
 
-      # The username reg service should be running.
-      - name: Check username-reg service
-        run: |
-          if [ -z "$(docker compose ps -q username-reg)" ]; then
-            echo "Data service exited unexpectedly"
-            exit 1
-          fi
+      # # The username reg service should be running.
+      # - name: Check username-reg service
+      #   run: |
+      #     if [ -z "$(docker compose ps -q username-reg)" ]; then
+      #       echo "Data service exited unexpectedly"
+      #       exit 1
+      #     fi
 
-      # The dashboard service should be running.
-      - name: Check dashboard service
-        run: |
-          if [ -z "$(docker compose ps -q dashboard)" ]; then
-            echo "Data service exited unexpectedly"
-            exit 1
-          fi
+      # # The dashboard service should be running.
+      # - name: Check dashboard service
+      #   run: |
+      #     if [ -z "$(docker compose ps -q dashboard)" ]; then
+      #       echo "Data service exited unexpectedly"
+      #       exit 1
+      #     fi
 
-      # The db service should be running.
-      - name: Check db service
-        run: |
-          if [ -z "$(docker compose ps -q db)" ]; then
-            exit 1
-          fi
+      # # The db service should be running.
+      # - name: Check db service
+      #   run: |
+      #     if [ -z "$(docker compose ps -q db)" ]; then
+      #       exit 1
+      #     fi
 
-      # The hyperdrive-monorepo service should be running.
-      - name: Check hyperdrive-monorepo service
-        run: |
-          if [ -z "$(docker compose ps -q hyperdrive-monorepo)" ]; then
-            echo "Hyperdrive monorepo service exited unexpectedly"
-            exit 1
-          fi
+      # # The hyperdrive-monorepo service should be running.
+      # - name: Check hyperdrive-monorepo service
+      #   run: |
+      #     if [ -z "$(docker compose ps -q hyperdrive-monorepo)" ]; then
+      #       echo "Hyperdrive monorepo service exited unexpectedly"
+      #       exit 1
+      #     fi
