Add service checks

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,8 +36,61 @@ jobs:
           source .env
           docker compose up -d
 
-      - name: Sleep for 10 seconds
-        run: sleep 10
+      - name: Check mine service
+        run: |
+          DIRNAME=$(basename $(pwd))
+          MINE_ERROR=$(docker wait $(DIRNAME)-mine-1)
+          if [ $MINE_ERROR -ne 0 ]; then
+            echo "Mine service exited with an error"
+            exit 1
+          fi
 
-      - name: Check services
-        run: docker compose ps -a
+      - name: Check fund Accounts service
+        run: |
+          DIRNAME=$(basename $(pwd))
+          FUND_ACCOUNTS_ERROR=$(docker wait $(DIRNAME)-fund-accounts-1)
+          if [ $FUND_ACCOUNTS_ERROR -ne 0 ]; then
+            echo "Fund accounts service exited with an error"
+            exit 1
+          fi
+
+      - name: Check ethereum service
+        run: |
+          if [ -z $(docker compose ps -q ethereum) ]; then
+            echo "Ethereum service exited unexpectedly"
+            exit 1
+          fi
+
+      - name: Check artifacts service
+        run: |
+          if [ -z $(docker compose ps -q artifacts) ]; then
+            echo "Artifacts service exited unexpectedly"
+            exit 1
+          fi
+
+      - name: Check checkpoint-bot service
+        run: |
+          if [ -z $(docker compose ps -q checkpoint-bot) ]; then
+            echo "Checkpoint bot service exited unexpectedly"
+            exit 1
+          fi
+
+      - name: Check data service
+        run: |
+          if [ -z $(docker compose ps -q data) ]; then
+            echo "Data service exited unexpectedly"
+            exit 1
+          fi
+
+      - name: Check db service
+        run: |
+          if [ -z $(docker compose ps -q db) ]; then
+            exit 1
+          fi
+
+      - name: Check hyperdrive-monorepo service
+        run: |
+          if [ -z $(docker compose ps -q hyperdrive-monorepo) ]; then
+            echo "Hyperdrive monorepo service exited unexpectedly"
+            exit 1
+          fi
